development:
  adapter: postgresql
  database: honkr ##could have two different names, and refer to them
  #in the if statement in environments.rb
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: honkr
  pool: 5
  timeout: 5000  